package io.github.synapse4j.data;

import lombok.AccessLevel;
import lombok.NoArgsConstructor;

/**
 * The well-known values for the role of a {@link ChatMessage}.
 *
 * <p>
 * Roles are plain strings, not an {@code enum}, so that a provider or an application can use a role
 * this library has never heard of. These constants are the vocabulary the mainstream protocols
 * agree on. A provider's own spelling is the adapter's business, not the shared model's: one
 * protocol calls the assistant role <em>model</em>, another has an extra <em>developer</em> role,
 * and both are handled where the request is translated.
 *
 * <p>
 * A holder of constants rather than a data class: it is final, and it cannot be instantiated.
 */
@NoArgsConstructor(access = AccessLevel.PRIVATE)
public final class ChatRole {

    /** Instructions from the application that frame everything else. */
    public static final String SYSTEM = "system";

    /** Input from the end user. */
    public static final String USER = "user";

    /** Output generated by the model. */
    public static final String ASSISTANT = "assistant";

    /**
     * The result of a tool call, sent back by the application. Protocols without a role of their own
     * for it carry the same content inside a {@link #USER} message, and the adapter moves it where
     * that protocol wants it.
     */
    public static final String TOOL = "tool";
}
