package io.github.synapse4j.data;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * A tool the model may call: what it is called, what it does, and what arguments it takes.
 *
 * <p>
 * The arguments schema is JSON text rather than a parsed tree, for the same reason
 * {@link ToolCallPart} keeps its arguments as text: this library does not bind a JSON library, so
 * the schema is generated by the codec the application chose.
 *
 * <p>
 * A tool carries its own {@link ProviderExtras} bag, like every other node. Where the adapter merges
 * that bag is part of the adapter's contract; it is the only way to reach a provider field that the
 * wire nests deeper than the fields modelled here.
 *
 * <p>
 * Built-in tools — a search or a code interpreter the provider runs itself — have a different shape
 * and no argument schema, so they are not this type. When they are modelled they belong in a
 * subclass, which is why this class stays open.
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
public class ToolDefinition {

    /** Name the model calls the tool by; the application resolves it against its own registry. */
    private String name;

    /** What the tool does, which is how the model decides whether to call it. */
    private String description;

    /** The arguments schema, as JSON Schema text. */
    private String inputSchema;

    /** Provider-specific fields to merge into this tool when the request is sent. */
    private final ProviderExtras extras = new ProviderExtras();

}
