package io.github.synapse4j.jackson;

import java.lang.reflect.Type;
import java.util.Map;
import java.util.Objects;

import com.github.victools.jsonschema.generator.SchemaGenerator;

import io.github.synapse4j.schema.AbstractJsonCodec;
import io.github.synapse4j.schema.JsonSchema;
import tools.jackson.databind.JavaType;
import tools.jackson.databind.json.JsonMapper;
import tools.jackson.databind.node.ObjectNode;

/**
 * A {@link io.github.synapse4j.schema.JsonCodec} over Jackson and victools: values are (de)serialized
 * with a {@link JsonMapper}, and each schema is generated by a victools {@link SchemaGenerator}.
 *
 * <p>
 * Both halves come from the same mapper on purpose. A schema is only worth generating if it describes
 * the JSON the mapper really moves, so the mapper is what tells the generator which properties exist,
 * what they are called and in what order — see {@link JacksonPropertyDiscovery}. Where the mapper answers
 * differently for writing than for reading, the two schemas differ with it.
 *
 * <p>
 * What a schema should say beyond that is decided in {@link JacksonSchemaGenerators}, so a caller who
 * wants other choices builds their own generators and passes them to
 * {@link #JacksonJsonCodec(JsonMapper, SchemaGenerator, SchemaGenerator)}.
 *
 * <p>
 * Every dependency on Jackson and victools lives here, not in the core: the codec is the module's whole
 * reason to exist, and an application that wants another JSON library implements
 * {@link io.github.synapse4j.schema.JsonCodec} against a module of its own instead. Instances hold no
 * state of their own and are shareable between threads — the mapper and the generators are guarded
 * where they are not.
 */
public class JacksonJsonCodec extends AbstractJsonCodec {

    private final JsonMapper jsonMapper;

    private final SchemaGenerator encodeSchemaGenerator;

    private final SchemaGenerator decodeSchemaGenerator;

    /**
     * Creates a codec with a default mapper and generators over it.
     *
     * <p>
     * The mapper is a plain {@link JsonMapper} with Jackson's own defaults, which means property names
     * come out as the Java names — the behaviour an application gets from "just serialize this". Pass a
     * mapper to one of the other constructors to change that, and both schemas follow.
     */
    public JacksonJsonCodec() {
        this(JsonMapper.builder().build());
    }

    /**
     * Creates a codec with the given mapper and generators over it.
     *
     * @param jsonMapper the mapper to bind values with; must not be {@code null}
     */
    public JacksonJsonCodec(JsonMapper jsonMapper) {
        this(jsonMapper, JacksonSchemaGenerators.encodeSchemaGenerator(jsonMapper),
                JacksonSchemaGenerators.decodeSchemaGenerator(jsonMapper));
    }

    /**
     * Creates a codec with the given mapper and schema generators.
     *
     * @param jsonMapper            the mapper to bind values with; must not be {@code null}
     * @param encodeSchemaGenerator the generator for the schema of what this codec writes; must not
     *                                  be {@code null}
     * @param decodeSchemaGenerator the generator for the schema of what this codec reads; must not be
     *                                  {@code null}
     */
    public JacksonJsonCodec(JsonMapper jsonMapper, SchemaGenerator encodeSchemaGenerator,
            SchemaGenerator decodeSchemaGenerator) {
        this.jsonMapper = Objects.requireNonNull(jsonMapper, "jsonMapper must not be null");
        this.encodeSchemaGenerator = Objects
                .requireNonNull(encodeSchemaGenerator, "encodeSchemaGenerator must not be null");
        this.decodeSchemaGenerator = Objects
                .requireNonNull(decodeSchemaGenerator, "decodeSchemaGenerator must not be null");
    }

    @Override
    public JsonSchema generateEncodeSchema(Type type) {
        return schema(encodeSchemaGenerator, type);
    }

    @Override
    public JsonSchema generateDecodeSchema(Type type) {
        return schema(decodeSchemaGenerator, type);
    }

    @Override
    protected String encodeValue(Object value) {
        return jsonMapper.writeValueAsString(value);
    }

    @Override
    protected <T> T decodeValue(String json, Type type) {
        return jsonMapper.readValue(json, jsonMapper.getTypeFactory().constructType(type));
    }

    private JsonSchema schema(SchemaGenerator schemaGenerator, Type type) {
        ObjectNode schemaNode = generateSchema(schemaGenerator, type);
        JavaType mapType = jsonMapper.getTypeFactory().constructMapType(Map.class, String.class, Object.class);
        return JsonSchema.fromMap(jsonMapper.convertValue(schemaNode, mapType));
    }

    /**
     * Runs one generation, alone.
     *
     * <p>
     * A victools generator keeps state while it walks a type, and two threads walking at once corrupt
     * each other's run — the same failure another library guards against with a synchronized block.
     * Victools' generators are handed to the constructor as they are, so the guard has to be here.
     * Schemas are generated while a request is built, not per token, so the lock costs nothing.
     */
    private static ObjectNode generateSchema(SchemaGenerator schemaGenerator, Type type) {
        synchronized (schemaGenerator) {
            return schemaGenerator.generateSchema(type);
        }
    }

}
