package io.github.synapse4j.jackson;

import java.io.InputStream;
import java.io.OutputStream;
import java.lang.reflect.Type;
import java.util.Map;

import org.jspecify.annotations.Nullable;

import com.github.victools.jsonschema.generator.SchemaGenerator;

import io.github.synapse4j.json.AbstractJsonCodec;
import io.github.synapse4j.json.JsonReader;
import io.github.synapse4j.json.JsonSchema;
import io.github.synapse4j.json.JsonWriter;
import tools.jackson.core.StreamReadFeature;
import tools.jackson.core.StreamWriteFeature;
import tools.jackson.core.json.JsonFactory;
import tools.jackson.databind.JavaType;
import tools.jackson.databind.json.JsonMapper;
import tools.jackson.databind.node.ObjectNode;

import lombok.NonNull;

/**
 * A {@link io.github.synapse4j.json.JsonCodec} over Jackson and victools: values are (de)serialized
 * with a {@link JsonMapper}, and each schema is generated by a victools {@link SchemaGenerator}.
 *
 * <p>
 * Both halves come from the same mapper on purpose. A schema is only worth generating if it describes
 * the JSON the mapper really moves, so the mapper is what tells the generator which properties exist,
 * what they are called and in what order — see {@link JacksonPropertyDiscovery}. Where the mapper answers
 * differently for writing than for reading, the two schemas differ with it.
 *
 * <p>
 * What a schema should say beyond that is decided in {@link JacksonSchemaGenerators}, so a caller who
 * wants other choices builds their own generators and passes them to
 * {@link #JacksonJsonCodec(JsonMapper, SchemaGenerator, SchemaGenerator)}.
 *
 * <p>
 * The token-level {@link JsonWriter} and {@link JsonReader} are built on a factory derived from the
 * same mapper's, so a document written or read token by token is parsed and encoded under the same
 * features as one bound through the mapper — only the two auto-close features differ, and
 * deliberately so.
 *
 * <p>
 * Every dependency on Jackson and victools lives here, not in the core: the codec is the module's whole
 * reason to exist, and an application that wants another JSON library implements
 * {@link io.github.synapse4j.json.JsonCodec} against a module of its own instead. Instances hold no
 * state of their own and are shareable between threads — the mapper and the generators are guarded
 * where they are not.
 */
public class JacksonJsonCodec extends AbstractJsonCodec {

    private final JsonMapper jsonMapper;

    private final SchemaGenerator encodeSchemaGenerator;

    private final SchemaGenerator decodeSchemaGenerator;

    /**
     * The factory the token-level writer and reader come from: the mapper's own, with the two
     * auto-close features turned off.
     *
     * <p>
     * The sink and the source belong to the caller of {@link #writer(OutputStream)} and
     * {@link #reader(InputStream)}, so neither adapter may close them — and since a
     * {@code JsonParser} has no per-instance configuration, the factory is the only place the setting
     * can be made. The mapper's factory is rebuilt rather than configured in place, so a mapper the
     * application passed in is left as it was.
     */
    private final JsonFactory tokenStreamFactory;

    /**
     * Creates a codec with a default mapper and generators over it.
     *
     * <p>
     * The mapper is a plain {@link JsonMapper} with Jackson's own defaults, which means property names
     * come out as the Java names — the behaviour an application gets from "just serialize this". Pass a
     * mapper to one of the other constructors to change that, and both schemas follow.
     */
    public JacksonJsonCodec() {
        this(JsonMapper.builder().build());
    }

    /**
     * Creates a codec with the given mapper and generators over it.
     *
     * @param jsonMapper the mapper to bind values with; must not be {@code null}
     */
    public JacksonJsonCodec(JsonMapper jsonMapper) {
        this(jsonMapper, JacksonSchemaGenerators.encodeSchemaGenerator(jsonMapper),
                JacksonSchemaGenerators.decodeSchemaGenerator(jsonMapper));
    }

    /**
     * Creates a codec with the given mapper and schema generators.
     *
     * @param jsonMapper            the mapper to bind values with; must not be {@code null}
     * @param encodeSchemaGenerator the generator for the schema of what this codec writes; must not
     *                                  be {@code null}
     * @param decodeSchemaGenerator the generator for the schema of what this codec reads; must not be
     *                                  {@code null}
     */
    public JacksonJsonCodec(@NonNull JsonMapper jsonMapper, @NonNull SchemaGenerator encodeSchemaGenerator,
            @NonNull SchemaGenerator decodeSchemaGenerator) {
        this.jsonMapper = jsonMapper;
        this.encodeSchemaGenerator = encodeSchemaGenerator;
        this.decodeSchemaGenerator = decodeSchemaGenerator;
        this.tokenStreamFactory = jsonMapper.tokenStreamFactory()
                .rebuild()
                .disable(StreamReadFeature.AUTO_CLOSE_SOURCE)
                .disable(StreamWriteFeature.AUTO_CLOSE_TARGET)
                .build();
    }

    @Override
    public JsonWriter writer(OutputStream out) {
        return JacksonJsonWriter.open(tokenStreamFactory, jsonMapper, out);
    }

    @Override
    public JsonReader reader(InputStream in) {
        return JacksonJsonReader.open(tokenStreamFactory, in);
    }

    @Override
    public JsonSchema generateEncodeSchema(Type type) {
        return schema(encodeSchemaGenerator, type);
    }

    @Override
    public JsonSchema generateDecodeSchema(Type type) {
        return schema(decodeSchemaGenerator, type);
    }

    @Override
    protected String encodeValue(@Nullable Object value) {
        return jsonMapper.writeValueAsString(value);
    }

    @Override
    protected <T> @Nullable T decodeValue(String json, Type type) {
        return jsonMapper.readValue(json, jsonMapper.getTypeFactory().constructType(type));
    }

    private JsonSchema schema(SchemaGenerator schemaGenerator, Type type) {
        ObjectNode schemaNode = generateSchema(schemaGenerator, type);
        JavaType mapType = jsonMapper.getTypeFactory().constructMapType(Map.class, String.class, Object.class);
        return JsonSchema.fromMap(jsonMapper.convertValue(schemaNode, mapType));
    }

    /**
     * Runs one generation, alone.
     *
     * <p>
     * A victools generator keeps state while it walks a type, and two threads walking at once corrupt
     * each other's run — the same failure another library guards against with a synchronized block.
     * Victools' generators are handed to the constructor as they are, so the guard has to be here.
     * Schemas are generated while a request is built, not per token, so the lock costs nothing.
     */
    private static ObjectNode generateSchema(SchemaGenerator schemaGenerator, Type type) {
        synchronized (schemaGenerator) {
            return schemaGenerator.generateSchema(type);
        }
    }

}
